default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: tutorial_development
  pool: 5
  username: buba
  password: password1

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: tutorial_test
  pool: 5
  username: buba
  password: password1

production:
  <<: *default
  database: tutorial_production
  username: buba
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
