# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d65d3b53b1997587103e1e8fc5db2ce4926f0780fda043d494423f23e9e2f62f1bff6a0b9e3d0650a00239d7381288c18a6d08c1ba6b4bc1613f3eb39827efa

test:
  secret_key_base: a96fc0c49be1b3eab09c1b063a241b6b242e95951260c7d1babadacdcbed3ed3fce87f584ef475ce3e6ec5e82f292f6674b0f3115e4226c8775ab582859bbc33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
